package view;

import DAO.ProdutoDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produtos;

public class TelaConsultaProd extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaCli
     */
    public TelaConsultaProd() {
        initComponents();
        
        btnConsultar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        txtPK_ID = new javax.swing.JTextField();
        txtDS_MODELO = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        chkSomenteEstoque = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Produtos");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lblCodigo.setText("Código:");

        lblProduto.setText("Produto:");

        txtPK_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPK_IDActionPerformed(evt);
            }
        });
        txtPK_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPK_IDKeyTyped(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        chkSomenteEstoque.setText("Somente Produtos com Estoque");
        chkSomenteEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSomenteEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPK_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtDS_MODELO))
                        .addGap(59, 59, 59)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkSomenteEstoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtPK_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDS_MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSomenteEstoque)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Vlr Unitário", "Qtd Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addGap(43, 43, 43)
                .addComponent(btnAlterar)
                .addGap(41, 41, 41)
                .addComponent(btnDeletar)
                .addGap(46, 46, 46)
                .addComponent(btnFechar)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnDeletar)
                    .addComponent(btnAlterar)
                    .addComponent(btnFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        int id = 0, linha = 0, QtdEstoque = 0;
        String produto = "";
        double VlrUnitario = 0.00;

        linha = tblResultados.getSelectedRow();

        id = Integer.parseInt(tblResultados.getValueAt(linha, 0).toString());
        produto = tblResultados.getValueAt(linha, 1).toString();
        VlrUnitario = Double.parseDouble(tblResultados.getValueAt(linha, 2).toString());
        QtdEstoque = Integer.parseInt(tblResultados.getValueAt(linha, 3).toString());

        Produtos objProduto = new Produtos();

        objProduto.setCodigoProduto(id);
        objProduto.setNomeProduto(produto);
        objProduto.setPrecoProduto(VlrUnitario);
        objProduto.setEstoqueProduto(QtdEstoque);

        TelaCadProdutos frame = new TelaCadProdutos(objProduto);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        TelaCadProdutos tcp = new TelaCadProdutos();
        tcp.setLocationRelativeTo(null);
        tcp.setVisible(true);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int id = 0, linha = 0, resultado = 0;
        String NomeProd = "";
        boolean retVen, retDel, retIni = false;
        Object[] opcao = { "Sim", "Não" };

        linha = tblResultados.getSelectedRow();

        id = Integer.parseInt(tblResultados.getValueAt(linha, 0).toString());
        NomeProd = tblResultados.getValueAt(linha,1).toString();
        
        retVen = ProdutoDAO.ValidaVendasProduto(id);
        
        if(retVen){
           JOptionPane.showMessageDialog(this, "Não é possível excluir o produto"+
                String.valueOf(id) +" - "+ NomeProd + " pois o mesmo tem Vendas vinculadas ao seu cadastro.\n");
   
        }else{
            resultado = JOptionPane.showOptionDialog(null, "Deseja mesmo excluir o produto "+
                String.valueOf(id) +" - "+ NomeProd + " ?",
                "Deletar Produto",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcao, opcao[1]);
            
            if(resultado == 1){
                return;
            }

            retDel = ProdutoDAO.excluir(id);

            if (retDel) {
                JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Produto.");
            }
            btnConsultar.doClick();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void chkSomenteEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSomenteEstoqueActionPerformed

    }//GEN-LAST:event_chkSomenteEstoqueActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int TG_ESTOQUE = 0;

        if(chkSomenteEstoque.isSelected()){
            TG_ESTOQUE = 1;
        }else{
            TG_ESTOQUE = 0;
        }

        if (txtDS_MODELO.getText().trim().equals("") && txtPK_ID.getText().trim().equals("")) {
            ArrayList<Produtos> listaProduto = ProdutoDAO.listar(TG_ESTOQUE);

            DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
            modelo.setRowCount(0);

            for (Produtos Produto : listaProduto) {
                modelo.addRow(new String[]{String.valueOf(Produto.getCodigoProduto()),
                    Produto.getNomeProduto(),
                    String.valueOf(Produto.getPrecoProduto()),
                    String.valueOf(Produto.getEstoqueProduto())
                });
            }
        } else if ((!(txtDS_MODELO.getText().trim().equals("")) && !(txtPK_ID.getText().trim().equals("")))) {

            String NomeProd = txtDS_MODELO.getText();
            int CodProduto = Integer.parseInt(txtPK_ID.getText());

            ArrayList<Produtos> listaProduto = ProdutoDAO.buscarProdutoNomeCodigo(NomeProd, CodProduto, TG_ESTOQUE);

            DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
            modelo.setRowCount(0);

            for (Produtos Produto : listaProduto) {
                modelo.addRow(new String[]{String.valueOf(Produto.getCodigoProduto()),
                    Produto.getNomeProduto(),
                    String.valueOf(Produto.getPrecoProduto()),
                    String.valueOf(Produto.getEstoqueProduto())
                });
            }
        } else if ((!(txtDS_MODELO.getText().trim().equals("")) && (txtPK_ID.getText().trim().equals("")))) {

            String NomeProd = txtDS_MODELO.getText();

            ArrayList<Produtos> listaProduto = ProdutoDAO.buscarProdutoNome(NomeProd, TG_ESTOQUE);

            DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
            modelo.setRowCount(0);

            for (Produtos Produto : listaProduto) {
                modelo.addRow(new String[]{String.valueOf(Produto.getCodigoProduto()),
                    Produto.getNomeProduto(),
                    String.valueOf(Produto.getPrecoProduto()),
                    String.valueOf(Produto.getEstoqueProduto())
                });

            }
        } else if (((txtDS_MODELO.getText().trim().equals("")) && !(txtPK_ID.getText().trim().equals("")))) {

            int CodProduto = Integer.parseInt(txtPK_ID.getText());

            ArrayList<Produtos> listaProduto = ProdutoDAO.buscarProdutoCodigo(CodProduto, TG_ESTOQUE);

            DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
            modelo.setRowCount(0);

            for (Produtos Produto : listaProduto) {
                modelo.addRow(new String[]{String.valueOf(Produto.getCodigoProduto()),
                    Produto.getNomeProduto(),
                    String.valueOf(Produto.getPrecoProduto()),
                    String.valueOf(Produto.getEstoqueProduto())
                });

            }
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtPK_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPK_IDKeyTyped
        if (txtPK_ID.getText().length() >= 10) {
            evt.consume();
        }

        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9'))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtPK_IDKeyTyped

    private void txtPK_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPK_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPK_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JCheckBox chkSomenteEstoque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtDS_MODELO;
    private javax.swing.JTextField txtPK_ID;
    // End of variables declaration//GEN-END:variables
}
