package view;


import DAO.VendasDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import model.VendasItem;


public class TelaVendasItens extends javax.swing.JFrame {
    TelaVendasCabecalho VendasCab;
    
    TelaBuscaProduto BuscaProd = null;
    
    TelaVendasItens VendasItem = this;
    
    VendasItem objItem = null; 
    public int Linha = -1;
    public int ProdTemp = 0;
    
    public TelaVendasItens() {
        initComponents();
    }
    
    public TelaVendasItens(VendasItem objItem, TelaVendasCabecalho VendasCab){
        this.objItem = objItem;
        this.VendasCab = VendasCab;
        
        initComponents();
    }
    
    public TelaVendasItens(VendasItem objItem, TelaVendasCabecalho VendasCab, int linha){
        this.objItem = objItem;
        this.VendasCab = VendasCab;
        this.Linha = linha;
        
        initComponents();
      
        txtFK_PRODUTO.setText(String.valueOf(objItem.getCodProduto()));
        txtQT_MOVIMENTO.setText(String.valueOf(objItem.getQtMovimento()));
        txtVL_PREUNI.setText(String.valueOf(objItem.getVlUnitario()));
        txtVL_PRETOT.setText(String.valueOf(objItem.getVlTotal()));
        txtVL_DESCONTO.setText(String.valueOf(objItem.getVlDesconto()));
        
        txtFK_PRODUTO.setEditable(false);
        btnBUSCAPROD.setEnabled(false);
        
        String NomeProd = "";
        
        NomeProd = VendasDAO.RetornaNomeProduto(objItem.getCodProduto());
        txtDS_PRODUTO.setText(NomeProd);
        ProdTemp = objItem.getCodProduto();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFK_PRODUTO = new javax.swing.JTextField();
        txtDS_PRODUTO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQT_MOVIMENTO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVL_DESCONTO = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVL_PREUNI = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVL_PRETOT = new javax.swing.JFormattedTextField();
        btnBUSCAPROD = new javax.swing.JButton();
        btnFINALIZAR = new javax.swing.JButton();
        btnVOLTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item da Venda");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(584, 400));

        jLabel1.setText("Produto: ");

        txtFK_PRODUTO.setBackground(new java.awt.Color(255, 255, 204));
        txtFK_PRODUTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFK_PRODUTOFocusLost(evt);
            }
        });
        txtFK_PRODUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFK_PRODUTOActionPerformed(evt);
            }
        });
        txtFK_PRODUTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFK_PRODUTOKeyTyped(evt);
            }
        });

        txtDS_PRODUTO.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDS_PRODUTO.setEnabled(false);

        jLabel6.setText("Quantidade:");

        txtQT_MOVIMENTO.setBackground(new java.awt.Color(255, 255, 204));
        txtQT_MOVIMENTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQT_MOVIMENTOFocusLost(evt);
            }
        });
        txtQT_MOVIMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQT_MOVIMENTOActionPerformed(evt);
            }
        });
        txtQT_MOVIMENTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQT_MOVIMENTOKeyTyped(evt);
            }
        });

        jLabel7.setText("Desconto(%)");

        txtVL_DESCONTO.setBackground(new java.awt.Color(255, 255, 204));
        txtVL_DESCONTO.setText("0.00");
        txtVL_DESCONTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVL_DESCONTOFocusLost(evt);
            }
        });
        txtVL_DESCONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVL_DESCONTOActionPerformed(evt);
            }
        });
        txtVL_DESCONTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVL_DESCONTOKeyTyped(evt);
            }
        });

        jLabel2.setText("Pre. Uni.:");

        txtVL_PREUNI.setBackground(new java.awt.Color(255, 255, 204));
        txtVL_PREUNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVL_PREUNIFocusLost(evt);
            }
        });
        txtVL_PREUNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVL_PREUNIActionPerformed(evt);
            }
        });
        txtVL_PREUNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVL_PREUNIKeyTyped(evt);
            }
        });

        jLabel4.setText("Pre. Tot.:");

        txtVL_PRETOT.setEditable(false);
        txtVL_PRETOT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnBUSCAPROD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa_icon.png"))); // NOI18N
        btnBUSCAPROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUSCAPRODActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVL_DESCONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQT_MOVIMENTO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFK_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(btnBUSCAPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVL_PREUNI, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDS_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVL_PRETOT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFK_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDS_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBUSCAPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQT_MOVIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtVL_PREUNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVL_DESCONTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtVL_PRETOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnFINALIZAR.setText("Confirmar");
        btnFINALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFINALIZARActionPerformed(evt);
            }
        });

        btnVOLTAR.setText("Cancelar");
        btnVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOLTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnFINALIZAR)
                .addGap(93, 93, 93)
                .addComponent(btnVOLTAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVOLTAR)
                    .addComponent(btnFINALIZAR))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFINALIZAR, btnVOLTAR});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFINALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFINALIZARActionPerformed
        int IdVenda = 0, IdProduto = 0, QtMovimento = 0, QtEstoque = 0;
        Double ValorProduto = 0.00, ValorTotal = 0.00, ValorDesconto = 0.00;
        boolean retorno = false;
               
        if(txtFK_PRODUTO.getText() .isEmpty() || txtQT_MOVIMENTO.getText() .isEmpty() 
            || txtVL_DESCONTO.getText() .isEmpty() || txtVL_PREUNI.getText() .isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo obrigatório não preenchido.");
            return;
        }
        
        IdProduto = Integer.parseInt(txtFK_PRODUTO.getText().trim());
        
        retorno = VendasDAO.ValidaProdutoExistente(IdProduto);

        if(!retorno){
            JOptionPane.showMessageDialog(this,"Produto não encontrado ou inativo no sistema","Erro no Produto",WARNING_MESSAGE);
            return;
        }
        
        if(Linha < 0){
            int size = VendasCab.listaItens.size();
        
            for (int i = 0; i < size; i++) {
                VendasItem item = VendasCab.listaItens.get(i);
                int Cod = 0;
                if (item != null) {
                    Object[] row = new Object[5];

                    Cod = item.getCodProduto();

                    if(Cod == IdProduto){
                        JOptionPane.showMessageDialog(this,"Produto já está na venda, favor alterar quantidade."
                                ,"Duplicidade de Produto",WARNING_MESSAGE);
                        return;
                    }
                }
            }
        }
        
        QtMovimento = Integer.parseInt(txtQT_MOVIMENTO.getText());
        ValorProduto = Double.valueOf(txtVL_PREUNI.getText());
        ValorTotal = Double.valueOf(txtVL_PRETOT.getText());
        ValorDesconto = Double.valueOf(txtVL_DESCONTO.getText());        
              
        QtEstoque = VendasDAO.ValidaQtEstoque(IdProduto);
        
        
        if(ValorProduto <= 0.00){
            JOptionPane.showMessageDialog(this, "Valor do produto inválido.");
            return; 
        }
        
        if(QtEstoque < QtMovimento){
            JOptionPane.showMessageDialog(this, 
                    "Quantidade insuficiente no estoque!"+
                    "\nProduto: "+String.valueOf(IdProduto) +" - " + txtDS_PRODUTO.getText()+
                    "\nQtd. Solicitada: " + String.valueOf(QtMovimento)+
                    "\nQtd. Disponível: " + String.valueOf(QtEstoque));
            return;
        }
        
        objItem.setIdVenda(IdVenda);
        objItem.setCodProduto(IdProduto);
        objItem.setQtMovimento(QtMovimento);
        objItem.setVlUnitario(ValorProduto);
        objItem.setVlTotal(ValorTotal);
        objItem.setVlDesconto(ValorDesconto);
              
        if(Linha >= 0){
            VendasCab.listaItens.set(Linha, objItem);
        }else{    
            VendasCab.listaItens.add(objItem);
        }
        
        VendasCab.ambientarGrade();
        this.dispose();
    }//GEN-LAST:event_btnFINALIZARActionPerformed

    private void btnVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOLTARActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVOLTARActionPerformed

    private void txtQT_MOVIMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQT_MOVIMENTOActionPerformed

    }//GEN-LAST:event_txtQT_MOVIMENTOActionPerformed

    private void txtQT_MOVIMENTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQT_MOVIMENTOFocusLost
        totalizarProduto();
    }//GEN-LAST:event_txtQT_MOVIMENTOFocusLost

    private void txtVL_PREUNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVL_PREUNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVL_PREUNIActionPerformed

    private void txtVL_PREUNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVL_PREUNIFocusLost
         totalizarProduto();
    }//GEN-LAST:event_txtVL_PREUNIFocusLost

    private void txtVL_DESCONTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVL_DESCONTOFocusLost
         totalizarProduto();
    }//GEN-LAST:event_txtVL_DESCONTOFocusLost

    private void txtVL_DESCONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVL_DESCONTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVL_DESCONTOActionPerformed

    private void txtQT_MOVIMENTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQT_MOVIMENTOKeyTyped
        if (txtQT_MOVIMENTO.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtQT_MOVIMENTOKeyTyped

    private void txtVL_DESCONTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVL_DESCONTOKeyTyped
        if (txtVL_DESCONTO.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_PERIOD)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtVL_DESCONTOKeyTyped

    private void txtFK_PRODUTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFK_PRODUTOKeyTyped
        if (txtFK_PRODUTO.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) ) {
            evt.consume();

        }
    }//GEN-LAST:event_txtFK_PRODUTOKeyTyped

    private void txtVL_PREUNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVL_PREUNIKeyTyped
        if (txtVL_DESCONTO.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_PERIOD)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtVL_PREUNIKeyTyped

    private void txtFK_PRODUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFK_PRODUTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFK_PRODUTOActionPerformed

    private void txtFK_PRODUTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFK_PRODUTOFocusLost
        boolean retorno = false;
        int CodProduto = 0;
        String NomeProd = "";
        Double VlProduto = 0.00;
        
        if(!txtFK_PRODUTO.getText().trim().equals("")){
            CodProduto = Integer.parseInt(txtFK_PRODUTO.getText().trim());
            
            retorno = VendasDAO.ValidaProdutoExistente(CodProduto);
            
            if(!retorno){
                JOptionPane.showMessageDialog(this,"Produto não encontrado.","Erro no Produto",WARNING_MESSAGE);
                txtDS_PRODUTO.setText("");
            }else{
                NomeProd = VendasDAO.RetornaNomeProduto(CodProduto);
                txtDS_PRODUTO.setText(NomeProd);
                
                if((ProdTemp > 0 && CodProduto != ProdTemp) || ProdTemp == 0){
                    VlProduto = VendasDAO.RetornaValorProduto(CodProduto);
                    txtVL_PREUNI.setText(String.valueOf(VlProduto)); 
                }
                               
            }
        }else{
            txtDS_PRODUTO.setText("");
        }   
    }//GEN-LAST:event_txtFK_PRODUTOFocusLost

    private void btnBUSCAPRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUSCAPRODActionPerformed
        this.BuscaProd = new TelaBuscaProduto(VendasItem);
        BuscaProd.setLocationRelativeTo(null);
        BuscaProd.show();   
    }//GEN-LAST:event_btnBUSCAPRODActionPerformed
    
    
    public void totalizarProduto(){
        int IdProduto = 0, QtMovimento = 0;
        Double ValorProduto = 0.00, ValorTotal = 0.00, ValorDesconto = 0.00;
        
        // VALIDAÇÃO DOS DADOS
        if(txtFK_PRODUTO.getText() .isEmpty() || txtQT_MOVIMENTO.getText() .isEmpty() ||
            txtVL_PREUNI.getText() .isEmpty()){
            return;
        }
        
        // ATRIBUIÇÃO DE VALORES
        IdProduto = Integer.parseInt(txtFK_PRODUTO.getText());
        QtMovimento = Integer.parseInt(txtQT_MOVIMENTO.getText());
        ValorProduto = Double.valueOf(txtVL_PREUNI.getText());
       
        ValorTotal = ValorProduto * Double.valueOf(QtMovimento);
        
        if(!txtVL_DESCONTO.getText() .isEmpty()){
            ValorDesconto = Double.valueOf(txtVL_DESCONTO.getText());        
            
            ValorTotal = ValorTotal - (ValorTotal * (ValorDesconto/100.00));
        }
        
        txtVL_PRETOT.setText(String.valueOf(ValorTotal));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendasItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBUSCAPROD;
    private javax.swing.JButton btnFINALIZAR;
    private javax.swing.JButton btnVOLTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtDS_PRODUTO;
    public javax.swing.JTextField txtFK_PRODUTO;
    private javax.swing.JTextField txtQT_MOVIMENTO;
    private javax.swing.JFormattedTextField txtVL_DESCONTO;
    private javax.swing.JFormattedTextField txtVL_PRETOT;
    public javax.swing.JFormattedTextField txtVL_PREUNI;
    // End of variables declaration//GEN-END:variables
}
