package view;

import DAO.ProdutoDAO;
import model.Produtos;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


public class TelaCadProdutos extends javax.swing.JFrame {

    Produtos objProduto = new Produtos();

    /**
     * Creates new form cadastro_produto2
     */
    public TelaCadProdutos() {
        initComponents();

    }

    public TelaCadProdutos(Produtos obj) {
        this.objProduto = obj;
        initComponents();

        txtPK_ID.setText(String.valueOf(objProduto.getCodigoProduto()));
        txtDS_MODELO.setText(objProduto.getNomeProduto());
        txtVL_PRECO.setText(String.valueOf(objProduto.getPrecoProduto()));
        txtQT_ESTOQUE.setText(String.valueOf(objProduto.getEstoqueProduto()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCodigoProduto = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        lblPrecoProduto = new javax.swing.JLabel();
        lblQuantidadeProduto = new javax.swing.JLabel();
        txtDS_MODELO = new javax.swing.JTextField();
        txtPK_ID = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtQT_ESTOQUE = new javax.swing.JTextField();
        txtVL_PRECO = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");
        setResizable(false);

        lblCodigoProduto.setText("Cod.Produto:");

        lblNomeProduto.setText("Nome do Produto:");

        lblPrecoProduto.setText("Preço Unitário:");

        lblQuantidadeProduto.setText("Qtde.Estoque:");

        txtDS_MODELO.setBackground(new java.awt.Color(255, 255, 204));
        txtDS_MODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDS_MODELOActionPerformed(evt);
            }
        });

        txtPK_ID.setEditable(false);
        txtPK_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPK_IDKeyTyped(evt);
            }
        });

        btnIncluir.setText("Salvar");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtQT_ESTOQUE.setBackground(new java.awt.Color(255, 255, 204));
        txtQT_ESTOQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQT_ESTOQUEActionPerformed(evt);
            }
        });
        txtQT_ESTOQUE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQT_ESTOQUEKeyTyped(evt);
            }
        });

        txtVL_PRECO.setBackground(new java.awt.Color(255, 255, 204));
        txtVL_PRECO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVL_PRECOActionPerformed(evt);
            }
        });
        txtVL_PRECO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVL_PRECOKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoProduto)
                                    .addComponent(lblPrecoProduto)
                                    .addComponent(lblQuantidadeProduto))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDS_MODELO, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtQT_ESTOQUE)
                                    .addComponent(txtPK_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVL_PRECO))))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnIncluir});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDS_MODELO, txtQT_ESTOQUE});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoProduto)
                    .addComponent(txtPK_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtDS_MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoProduto)
                    .addComponent(txtVL_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeProduto)
                    .addComponent(txtQT_ESTOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(42, 42, 42))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnIncluir});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDS_MODELO, txtPK_ID, txtQT_ESTOQUE});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        String NomeProd = "";
        Double PrecoUnit = 0.00;
        int QtdEstoque = 0;
        int id = 0;
        boolean retorno;

        if ((txtDS_MODELO.getText().trim().isEmpty()) || (txtVL_PRECO.getText().trim().isEmpty())
                || (txtQT_ESTOQUE.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(this,"Campo obrigatório não preenchido!");
            return;
        }
        
        NomeProd = txtDS_MODELO.getText();
        PrecoUnit = Double.valueOf(txtVL_PRECO.getText());
        QtdEstoque = Integer.parseInt(txtQT_ESTOQUE.getText());

        if (txtPK_ID.getText().trim().equals("")) {

            Produtos objProduto = new Produtos(NomeProd, PrecoUnit, QtdEstoque);

            retorno = ProdutoDAO.salvar(objProduto);

            if (retorno) {
                JOptionPane.showMessageDialog(this, "Dados incluidos com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao incluir dados.");
            }

        } else {

            id = Integer.parseInt(txtPK_ID.getText());

            Produtos objProduto = new Produtos(id, NomeProd, PrecoUnit, QtdEstoque);

            retorno = ProdutoDAO.alterar(objProduto);

            if (retorno) {
                JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar produto.");
            }

        }

        this.dispose();
    }//GEN-LAST:event_btnIncluirActionPerformed


    private void txtDS_MODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDS_MODELOActionPerformed


    }//GEN-LAST:event_txtDS_MODELOActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (txtDS_MODELO.getText().isEmpty() && txtVL_PRECO.getText().isEmpty() && txtQT_ESTOQUE.getText().isEmpty()) {
            this.dispose();

        } else {
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que seja cancelar?",
                    "Saída", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPK_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPK_IDKeyTyped

        if (txtPK_ID.getText().length() >= 5) {
            evt.consume();

        }

        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();

        }


    }//GEN-LAST:event_txtPK_IDKeyTyped

    private void txtQT_ESTOQUEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQT_ESTOQUEKeyTyped

        if (txtQT_ESTOQUE.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtQT_ESTOQUEKeyTyped

    private void txtQT_ESTOQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQT_ESTOQUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQT_ESTOQUEActionPerformed

    private void txtVL_PRECOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVL_PRECOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVL_PRECOActionPerformed

    private void txtVL_PRECOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVL_PRECOKeyTyped
        if (txtVL_PRECO.getText().length() >= 10) {
            evt.consume();

        }
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_PERIOD)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtVL_PRECOKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPrecoProduto;
    private javax.swing.JLabel lblQuantidadeProduto;
    private javax.swing.JTextField txtDS_MODELO;
    private javax.swing.JTextField txtPK_ID;
    private javax.swing.JTextField txtQT_ESTOQUE;
    private javax.swing.JTextField txtVL_PRECO;
    // End of variables declaration//GEN-END:variables

}
