DROP DATABASE floricultura;


create database floricultura;

use floricultura;

create table PRODUTOS(
	PK_ID int auto_increment not null,
		primary key(PK_ID),
	DS_MODELO varchar(40) not null,
	VL_PRECO numeric(8,2) not null,
	QT_ESTOQUE integer not null
);

INSERT INTO Produtos (DS_MODELO, VL_PRECO, QT_ESTOQUE) VALUES ('Flor de laranjeira', 10.00, 10);
INSERT INTO Produtos (DS_MODELO, VL_PRECO, QT_ESTOQUE) VALUES ('Rosas brancas', 15.00, 50);

INSERT INTO Produtos (DS_MODELO, VL_PRECO, QT_ESTOQUE) VALUES ('Buquê de girassóis', 30.00, 100);
INSERT INTO Produtos (DS_MODELO, VL_PRECO, QT_ESTOQUE) VALUES ('Lírios', 20.00, 50);
INSERT INTO Produtos (DS_MODELO, VL_PRECO, QT_ESTOQUE) VALUES ('Sementes variadas', 5.00, 5);

create table CLIENTES(
	PK_ID int auto_increment not null,
		primary key(PK_ID),
	DS_NOME varchar(60) not null,
	NR_CPF NUMERIC(11) unique not null,
    DT_NASCIMENTO DATE,
	DS_EMAIL varchar(40) not null,
	DS_TELEFONE varchar(30),
	DS_CEP varchar(10) not null,
	DS_ENDERECO varchar(60) not null,
	DS_CIDADE varchar(30) not null,
	DS_UF varchar(2) not null,
	DS_PAIS varchar(3) not null,
    TG_SEXO VARCHAR(1) not null,
    TG_ESTADOCIVIL VARCHAR(1) not null
);

INSERT INTO CLIENTES (DS_NOME,NR_CPF, DT_NASCIMENTO, DS_EMAIL, DS_TELEFONE, DS_CEP, DS_ENDERECO, DS_CIDADE, DS_UF,
	DS_PAIS, TG_SEXO, TG_ESTADOCIVIL) VALUES ("Carlos", 32145678989, '1997-12-01', 'email', '', 'cep','endereco','cidade','uf','BRA','M','S');

INSERT INTO CLIENTES (DS_NOME,NR_CPF, DT_NASCIMENTO, DS_EMAIL, DS_TELEFONE, DS_CEP, DS_ENDERECO, DS_CIDADE, DS_UF,
	DS_PAIS, TG_SEXO, TG_ESTADOCIVIL) VALUES ("José", 12789678905,  '1998-05-06', 'jose@gmail.com', '', '04578250','Rua dos Alpes, 20','São Paulo','SP','BRA','M','C');
 
 INSERT INTO CLIENTES (DS_NOME,NR_CPF, DT_NASCIMENTO, DS_EMAIL, DS_TELEFONE, DS_CEP, DS_ENDERECO, DS_CIDADE, DS_UF,
	DS_PAIS, TG_SEXO, TG_ESTADOCIVIL) VALUES ("Silvia", 45941258852, '1985-03-26', 'sil@senacedu.sp.br', '', '04512852','Avenida Treze, 1','Belo Horizonte','MG','BRA','F','D');
 
 INSERT INTO CLIENTES (DS_NOME,NR_CPF, DT_NASCIMENTO, DS_EMAIL, DS_TELEFONE, DS_CEP, DS_ENDERECO, DS_CIDADE, DS_UF,
	DS_PAIS, TG_SEXO, TG_ESTADOCIVIL) VALUES ("Fernando", 43841258852, '1985-03-26', 'fer1985@hotmail.com', '', '04512852','Avenida Atlantica, 1850','São Paulo','SP','BRA','M','C');
    
CREATE TABLE VENDAS_CABECALHO(
PK_ID int auto_increment not null,
	primary key(PK_ID),
FK_CLIENTE INT,
	FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTES (PK_ID),
VL_TOTAL NUMERIC(8,2),
DH_VENDA datetime,
TG_CANCELADO TINYINT DEFAULT 0,
DS_MOTIVOCANCELAMENTO VARCHAR(254) DEFAULT ''
);

INSERT INTO VENDAS_CABECALHO (FK_CLIENTE, VL_TOTAL, DH_VENDA) VALUES (1, 65.00, "2022-11-15 19:18:00");

INSERT INTO VENDAS_CABECALHO (FK_CLIENTE, VL_TOTAL, DH_VENDA) VALUES (2, 195.00, "2022-11-16 12:00:00");

CREATE TABLE VENDAS_ITEM(
PK_ID int auto_increment not null,
	primary key(PK_ID),
FK_VENDA INT,
	FOREIGN KEY (FK_VENDA) REFERENCES VENDAS_CABECALHO (PK_ID),
FK_PRODUTO INT,
	FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTOS (PK_ID),
QT_MOVIMENTO INT NOT NULL NOT NULL,
VL_PREUNI NUMERIC(8,2) NOT NULL,
VL_PRETOT NUMERIC(8,2) NOT NULL,
VL_DESCONTO NUMERIC(5,2)
);

INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(1, 1, 2,  10.00, 20.00, 0.00);

INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(1, 2, 3, 15.00, 45.00, 0.00);


INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(2, 1, 2, 10.00, 20.00, 0.00);

INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(2, 2, 3, 15.00, 45.00, 0.00);

INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(2, 3, 1, 30.00, 30.00, 0.00);

INSERT INTO VENDAS_ITEM (FK_VENDA, FK_PRODUTO , QT_MOVIMENTO, VL_PREUNI, VL_PRETOT, VL_DESCONTO) VALUES 
(2, 4, 5,  20.00, 100.00, 0.00);

CREATE TABLE USUARIOS(
PK_ID int auto_increment not null,
	primary key(PK_ID),
DS_NOME VARCHAR(30) NOT NULL,
DS_LOGIN VARCHAR(10) NOT NULL,
DS_SENHA VARCHAR(30) NOT NULL
);

INSERT INTO USUARIOS (DS_NOME, DS_LOGIN, DS_SENHA) VALUES ('Usuário','USER','1234');

CREATE VIEW VW_RELSINTETICO AS(
	SELECT
		VEN.PK_ID,
        VEN.DH_VENDA,
        VEN.FK_CLIENTE,
        VEN.VL_TOTAL,
        VEN.TG_CANCELADO,
        CASE WHEN TG_CANCELADO = 1
        THEN 'SIM'
        ELSE 'NÃO'
        END AS DS_CANCELADO,
        VEN.DS_MOTIVOCANCELAMENTO,
        CLI.DS_NOME,
        SUM(ITE.QT_MOVIMENTO) AS QT_PRODUTOS
	FROM VENDAS_CABECALHO VEN
    LEFT JOIN CLIENTES CLI ON CLI.PK_ID = VEN.FK_CLIENTE
	LEFT JOIN VENDAS_ITEM ITE ON ITE.FK_VENDA = VEN.PK_ID
	GROUP BY ITE.FK_VENDA
);
